### ISSUE TITLE
Checking a Promise without blocking?

### ISSUE THREAD

**Issue by Hoverbear** [dwrensha/capnp-rpc-rust#5] opened 2015-03-09 18:58 UTC
I haven't quite figured out how to create a "barrier" to wait for multiple requests.

Something like this:

``` rust
    println!("Issuing request_vote.");
    {
        let mut request = raft_client.request_vote_request();
        let mut builder = request.init();
        builder.set_term(0u64);
        builder.set_candidate_id(0u64);
        builder.set_last_log_index(0u64);
        builder.set_last_log_term(0u64);
        let mut promise = request.send();

        println!("Retrieving request_vote response.");
        let response = promise.wait().unwrap();
        let term = response.get_term();
        let vote_granted = response.get_vote_granted();

        println!("
            Term: {}
            voteGranted: {}
        ", term, vote_granted)
    }
```

Works fine for a single RPC. However because of `wait()` I'm not sure how to approach waiting on the results of multiple RPC calls without using extra threads. I don't see a sort of `has_responded()` type functionality. Do you have a suggestion?

**Comment by dwrensha** [comment] 2015-03-10 02:33
I think your best option in such cases is to spawn a new thread and synchronize using channels. The RPC system was designed with green threads in mind. Now that libgreen is gone, I think we may need to go back and revisit some assumptions.

**Comment by Hoverbear** [comment] 2015-03-10 14:20
It looks like [`wait()`](https://github.com/dwrensha/capnp-rpc-rust/blob/8da1b5e8f9c3bc5390f3508c88a413a88f0592a5/src/capability.rs#L123) is using `recv` on [`anwer_port`](https://github.com/dwrensha/capnproto-rust/blob/3139eff431fe3b4d9253d83de191b273e4d41420/src/capability.rs#L32)... It's possible we can use [`try_recv()`](http://doc.rust-lang.org/std/sync/mpsc/struct.Receiver.html#method.try_recv) to implement a `poll()` type function.

**Comment by Hoverbear** [comment] 2015-03-11 21:35
I got a bit of a draft implementation [here](https://github.com/Hoverbear/capnp-rpc-rust/commit/5c846758cf20448d008497b011f9774797913d80) but I think, as you discussed, it might be better to rethink things with syncbox or mio.

**Comment by Hoverbear** [comment] 2015-03-27 17:02
@dwrensha Any news on this?

**Comment by dwrensha** [comment] 2015-03-29 03:42
I'm okay with adding something like your `poll()` if it helps you get stuff done. Send me a pull request if you want to go that route. :)

Longer term, we clearly do need to rework our concurrency strategy. This is going to be a rather big project, and a lot of the interfaces will change.

I see at least two promising approaches for getting started on this: we could port the [KJ async library](https://capnproto.org/cxxrpc.html#event-loop-concurrency) to Rust, or we could build off of mio/syncbox.  I am personally partial to KJ because I'm familiar with it and it has proven to work well for capnproto-c++. A big difference between KJ and mio is that a KJ event loop is _single-threaded_, so it needs to worry less about atomic operations and synchronization. The flip side is that achieving actual parallelism with KJ can be a bit cumbersome. Tradeoffs abound.

**Comment by dwrensha** [comment] 2015-03-30 02:10
It looks like `mio::EventLoop` is more or less equivalent to `kj::EventPort`, so I think we should try to use it in any case. What's still unclear to me is whether we should use KJ-style promises, which are single-threaded, or syncbox-style futures, which might not be.

**Comment by Hoverbear** [comment] 2015-03-30 03:03
@carllerche have you looked at KJ-style promises?

**Comment by carllerche** [comment] 2015-03-30 04:08
I am not super familiar with KJ-style promises, but they are compared to JS promises.

Syncbox promises (which I plan on breaking out to a dedicated lib), are primarily async, but are able to block waiting for the value. They work with one thread or with many (they are thread safe and can be used to send values across threads).

I'm pretty sure that they would support whatever you need, if not let me know what is missing.

**Comment by dwrensha** [comment] 2015-04-28 14:16
Update: I've started playing around with porting KJ to Rust. Working name: GJ. https://github.com/dwrensha/gj

Looks like a big difference between GJ promises and Eventual futures is going to be that `GJ` does not require a `Send` bound on data that's passed through the `then()` method.

**Comment by carllerche** [comment] 2015-04-28 16:50
It would be fine to remove the default `Send` bound on eventual. Just bound `Future` by `Send` if `T: Send`. A lot of work has already gone into Eventual, it would be a shame to not be able to reuse it.

**Comment by dwrensha** [comment] 2015-04-28 17:34
@carllerche: I see that `Future::map()` has a signature like this:

``` rust
pub fn map<F, U>(self, f: F) -> Future<U, E>
        where F: FnOnce(T) -> U + Send + 'static,
              U: Send + 'static
```

Are you saying that this could be amended to the following?

``` rust
pub fn map<F, U>(self, f: F) -> Future<U, E>
        where F: FnOnce(T) -> U + 'static,
              U: 'static
```

This is important for my use case because I think I'll very often want to share `Rc` data between the callback and the caller.

**Comment by carllerche** [comment] 2015-04-30 17:37
So yeah, after thinking about it for a while, I think you are correct in that this is analogous to `Rc` vs. `Arc`. To support this, there would need to be `Future` and `NoSendFuture` (obviously not a good name). The problem is that there is no good way to define the `Async` trait to support both of these versions. I think that supporting both `Send` and non `Send` versions would be plausible when (if?) HKT lands.

The flip side is that the these futures won't be able to be sent across threads, which is something that I would have hoped to be able to do w/ this.

Hopefully one day we will get HKT and I can update Eventual for this case.

**Comment by dwrensha** [comment] 2016-01-11 19:39
This is fixed in the 0.6 release, which uses GJ: https://dwrensha.github.io/capnproto-rust/2016/01/11/async-rpc.html . You can now collect the results with `Promise::all()`.

**Closed as completed by dwrensha** 2016-01-11 19:39 UTC

**Comment by Hoverbear** [comment] 2016-01-12 20:16
Woo! Go Drew!

**Comment by dwrensha** [comment] 2016-01-12 20:25
@Hoverbear are you still confusing me with @zarvox? :)

**Comment by zarvox** [comment] 2016-01-12 20:38
We did meet at a Rust Meetup once.  @Hoverbear has sweet business cards. :)

**Comment by Hoverbear** [comment] 2016-01-12 23:12
@dwrensha David! Sigh.... Sorry.
